# Generated by Django 3.0.2 on 2020-03-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200310_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimedia',
            name='image',
        ),
    ]
