# Generated by Django 3.0.2 on 2020-03-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_multimedia_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimedia',
            old_name='audio',
            new_name='file',
        ),
    ]
