# Generated by Django 3.0.2 on 2020-03-10 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20200310_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Multimedia',
            new_name='ImageMedia',
        ),
    ]
