# Generated by Django 3.0.2 on 2020-03-10 15:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20200310_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AudioMedia',
            new_name='Audios',
        ),
        migrations.RenameModel(
            old_name='ImageMedia',
            new_name='Images',
        ),
    ]
