# Generated by Django 3.0.2 on 2020-03-10 15:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_auto_20200310_2050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audios',
            new_name='Audio',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
